### ISSUE TITLE
dbus是否能实现跨端通信

### ISSUE THREAD

**Issue by Hollow-cat** [rororwwww/QtDbusDemo#1]
你好！我最近也在学习dbus相关知识，想了解一下dbus能够实现不同机器之间的跨端通信吗？这方面资料比较少所以我比较疑惑。

**Comment by zekiyou** [comment]
你好 dbus的本质是基于linux domain socket即本地socket，一般是本地进程与进程的通信，跨机器我们一般用tcp/udp socket，可参考我另外一个socket网络编程聊天项目

**Comment by zekiyou** [comment]
资料的话 你可以先看看wiki百科 https://zh.wikipedia.org/zh-cn/D-Bus D-Bus是一个[进程间通信](https://zh.wikipedia.org/wiki/%E8%A1%8C%E7%A8%8B%E9%96%93%E9%80%9A%E8%A8%8A)及[远程过程调用](https://zh.wikipedia.org/wiki/%E8%BF%9C%E7%A8%8B%E8%BF%87%E7%A8%8B%E8%B0%83%E7%94%A8)机制，可以让多个不同的[计算机程序](https://zh.wikipedia.org/wiki/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A8%8B%E5%BA%8F)（即[进程](https://zh.wikipedia.org/wiki/%E8%A1%8C%E7%A8%8B)）在同一台电脑上同时进行通信[[4]](https://zh.wikipedia.org/zh-cn/D-Bus#cite_note-dbusovw-4)。D-Bus作为[freedesktop.org](https://zh.wikipedia.org/wiki/Freedesktop.org)项目的一部分，其设计目的是使[Linux](https://zh.wikipedia.org/wiki/Linux)[桌面环境](https://zh.wikipedia.org/wiki/%E6%A1%8C%E9%9D%A2%E7%8E%AF%E5%A2%83)（如[GNOME](https://zh.wikipedia.org/wiki/GNOME)与[KDE](https://zh.wikipedia.org/wiki/KDE)等）提供的服务标准化。 （注意⚠️：强调了同一台电脑）

**Comment by Hollow-cat** [comment]
感谢你的解答，我最近在尝试远程连接qt应用进行gui测试，在github上找到了一个项目https://github.com/uglide/RocketPilot ，它的原理就是用qtdbus进行通信，所以我在想能不能改造成跨端通信。

**Comment by zekiyou** [comment]
内网之间的跨端直接改成用socket，外网之间两台机器用花生壳做内网穿透或者公网ip即可

**Comment by Hollow-cat** [comment]
嗯明白了，我学习相关知识后进行尝试，感谢！
